// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetCallInfoData,
  GetCallInfoErrors,
  GetCallInfoResponses,
  GetCallMediaData,
  GetCallMediaErrors,
  GetCallMediaResponses,
  GetCallSnippetsData,
  GetCallSnippetsErrors,
  GetCallSnippetsResponses,
  GetPingV1TestPingGetData,
  GetPingV1TestPingGetErrors,
  GetPingV1TestPingGetResponses,
  JoinCallData,
  JoinCallErrors,
  JoinCallResponses,
  ListCallsData,
  ListCallsErrors,
  ListCallsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Ping
 */
export const getPingV1TestPingGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPingV1TestPingGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetPingV1TestPingGetResponses,
    GetPingV1TestPingGetErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/v1/test/ping",
    ...options,
  });

/**
 * Get Calls
 *
 * Retrieve list of calls for your organization.
 *
 * - Only public calls are returned (all private calls are excluded)
 * - Results are sorted by start time in descending order (newest first)
 */
export const listCalls = <ThrowOnError extends boolean = false>(
  options?: Options<ListCallsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListCallsResponses,
    ListCallsErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/v1/calls/",
    ...options,
  });

/**
 * Get Call
 *
 * Retrieve a call by its ID.
 *
 * - media_url is a presigned URL that expires in 24 hours
 */
export const getCallInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetCallInfoData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCallInfoResponses,
    GetCallInfoErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/v1/calls/{call_id}",
    ...options,
  });

/**
 * Get Media
 *
 * Retrieve a call's media URL and type by its ID.
 *
 * - media_url is a presigned URL that expires in 24 hours
 */
export const getCallMedia = <ThrowOnError extends boolean = false>(
  options: Options<GetCallMediaData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCallMediaResponses,
    GetCallMediaErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/v1/calls/{call_id}/media",
    ...options,
  });

/**
 * Get Call Snippets
 *
 * Retrieve a call's snippets by its ID.
 *
 * - snippets are sorted by created_at_utc in descending order (newest first)
 * - media_url is a presigned URL that expires in 24 hours
 * - transcript_turns are filtered to the snippet time range
 */
export const getCallSnippets = <ThrowOnError extends boolean = false>(
  options: Options<GetCallSnippetsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCallSnippetsResponses,
    GetCallSnippetsErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/v1/calls/{call_id}/snippets",
    ...options,
  });

/**
 * Join Call
 *
 * Join a call by creating a bot that will join the specified meeting URL.
 *
 * The bot will join the meeting and record it. Once the call is complete,
 * it can be processed and retrieved through other API endpoints.
 *
 * Multiple bots cannot be created for the same meeting URL within 2 minutes.
 */
export const joinCall = <ThrowOnError extends boolean = false>(
  options: Options<JoinCallData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    JoinCallResponses,
    JoinCallErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/v1/call_bots",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
