// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.staging.glyphic.ai" | (string & {});
};

/**
 * CallDetail
 *
 * Detail of a call used for viewing a call.
 */
export type CallDetail = {
  /**
   * Id
   */
  id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Companies
   */
  companies?: Array<CompanyPreview>;
  /**
   * Participants
   */
  participants?: Array<ParticipantPreview>;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * Duration
   */
  duration?: number | null;
  status: CallStatus;
  /**
   * Transcript Turns
   */
  transcript_turns?: Array<TranscriptTurn> | null;
  /**
   * Summary
   */
  summary?: string | null;
  media?: CallMedia | null;
  /**
   * Url Link
   */
  url_link?: string | null;
  /**
   * Insights
   */
  insights?: Array<CallInsight> | null;
};

/**
 * CallInsight
 *
 * Insight extracted from a call
 */
export type CallInsight = {
  /**
   * Name
   */
  name: string;
  /**
   * Value
   */
  value?: string | null;
};

/**
 * CallMedia
 *
 * Media URL and type for a call.
 */
export type CallMedia = {
  media_type?: MediaType | null;
  /**
   * Media Url
   */
  media_url?: string | null;
};

/**
 * CallPreview
 *
 * Preview of a call used for listing calls.
 */
export type CallPreview = {
  /**
   * Id
   */
  id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Companies
   */
  companies?: Array<CompanyPreview>;
  /**
   * Participants
   */
  participants?: Array<ParticipantPreview>;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * Duration
   */
  duration?: number | null;
  status: CallStatus;
};

/**
 * CallSnippet
 *
 * Snippet of a call.
 */
export type CallSnippet = {
  media?: CallMedia | null;
  /**
   * Start Seconds
   */
  start_seconds: number;
  /**
   * End Seconds
   */
  end_seconds: number;
  /**
   * Transcript Turns
   */
  transcript_turns?: Array<TranscriptTurn>;
};

/**
 * CallStatus
 */
export type CallStatus = {
  code: ProcessStatus;
};

/**
 * CompanyPreview
 */
export type CompanyPreview = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Domain
   */
  domain: string;
};

/**
 * CursorPagination
 *
 * Cursor-based pagination.
 */
export type CursorPagination = {
  /**
   * Next Cursor
   */
  next_cursor?: string | null;
  /**
   * Previous Cursor
   */
  previous_cursor?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * JoinCallRequest
 *
 * Request to join a call with a bot.
 */
export type JoinCallRequest = {
  /**
   * Meeting Url
   *
   * The URL of the meeting to join (e.g., Google Meet, Zoom, etc.)
   */
  meeting_url: string;
  /**
   * Title
   *
   * The title of the meeting to join
   */
  title?: string | null;
  /**
   * Participants
   *
   * The participants in the meeting
   */
  participants?: Array<Participant> | null;
};

/**
 * MediaType
 */
export type MediaType = "audio" | "video";

/**
 * PaginatedResponse[CallPreview]
 */
export type PaginatedResponseCallPreview = {
  /**
   * Data
   */
  data: Array<CallPreview>;
  pagination: CursorPagination;
};

/**
 * Participant
 */
export type Participant = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Email
   */
  email?: string | null;
};

/**
 * ParticipantPreview
 */
export type ParticipantPreview = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Id
   */
  id: number;
};

/**
 * ProcessStatus
 *
 * Status of a process.
 * NOTE: THIS AFFECTS THE API!!!
 * We need `UNKNOWN` here as a catch all for the API. It should NEVER be used
 * outside of the API.
 */
export type ProcessStatus =
  | "queued"
  | "in_progress"
  | "completed"
  | "failed"
  | "cancelled";

/**
 * TranscriptTurn
 */
export type TranscriptTurn = {
  /**
   * Party Id
   */
  party_id: number;
  /**
   * Turn Text
   */
  turn_text: string;
  /**
   * Timestamp
   */
  timestamp: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetPingV1TestPingGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/test/ping";
};

export type GetPingV1TestPingGetErrors = {
  /**
   * Unauthorized - Invalid or missing API key
   */
  401: unknown;
};

export type GetPingV1TestPingGetResponses = {
  /**
   * Response Get Ping V1 Test Ping Get
   *
   * Successful ping response
   */
  200: string;
};

export type GetPingV1TestPingGetResponse =
  GetPingV1TestPingGetResponses[keyof GetPingV1TestPingGetResponses];

export type ListCallsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Participant Email
     *
     * A participant's email to filter by (case insensitive). Only calls with this participant will be shown.
     */
    participant_email?: string | null;
    /**
     * Start Time From
     *
     * Filter calls starting from this time (UTC ISO 8601)
     */
    start_time_from?: string | null;
    /**
     * Start Time To
     *
     * Filter calls starting up to this time (UTC ISO 8601)
     */
    start_time_to?: string | null;
    /**
     * Title Filter
     *
     * Query to filter calls by call title.
     */
    title_filter?: string | null;
    /**
     * Cursor
     *
     * Cursor for pagination
     */
    cursor?: string | null;
    /**
     * Limit
     *
     * Number of items per page
     */
    limit?: number;
    /**
     * Direction
     *
     * Pagination direction
     */
    direction?: "next" | "prev";
  };
  url: "/v1/calls/";
};

export type ListCallsErrors = {
  /**
   * Unauthorized - Invalid or missing API key
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCallsError = ListCallsErrors[keyof ListCallsErrors];

export type ListCallsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseCallPreview;
};

export type ListCallsResponse = ListCallsResponses[keyof ListCallsResponses];

export type GetCallInfoData = {
  body?: never;
  path: {
    /**
     * Call Id
     */
    call_id: string;
  };
  query?: never;
  url: "/v1/calls/{call_id}";
};

export type GetCallInfoErrors = {
  /**
   * Unauthorized - Invalid or missing API key
   */
  401: unknown;
  /**
   * Call not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCallInfoError = GetCallInfoErrors[keyof GetCallInfoErrors];

export type GetCallInfoResponses = {
  /**
   * Successful Response
   */
  200: CallDetail;
};

export type GetCallInfoResponse =
  GetCallInfoResponses[keyof GetCallInfoResponses];

export type GetCallMediaData = {
  body?: never;
  path: {
    /**
     * Call Id
     */
    call_id: string;
  };
  query?: never;
  url: "/v1/calls/{call_id}/media";
};

export type GetCallMediaErrors = {
  /**
   * Unauthorized - Invalid or missing API key
   */
  401: unknown;
  /**
   * Call not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCallMediaError = GetCallMediaErrors[keyof GetCallMediaErrors];

export type GetCallMediaResponses = {
  /**
   * Successful Response
   */
  200: CallMedia;
};

export type GetCallMediaResponse =
  GetCallMediaResponses[keyof GetCallMediaResponses];

export type GetCallSnippetsData = {
  body?: never;
  path: {
    /**
     * Call Id
     */
    call_id: string;
  };
  query?: never;
  url: "/v1/calls/{call_id}/snippets";
};

export type GetCallSnippetsErrors = {
  /**
   * Unauthorized - Invalid or missing API key
   */
  401: unknown;
  /**
   * Call not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCallSnippetsError =
  GetCallSnippetsErrors[keyof GetCallSnippetsErrors];

export type GetCallSnippetsResponses = {
  /**
   * Response Get Call Snippets
   *
   * Successful Response
   */
  200: Array<CallSnippet>;
};

export type GetCallSnippetsResponse =
  GetCallSnippetsResponses[keyof GetCallSnippetsResponses];

export type JoinCallData = {
  body: JoinCallRequest;
  path?: never;
  query?: never;
  url: "/v1/call_bots";
};

export type JoinCallErrors = {
  /**
   * Unauthorized - Invalid or missing API key
   */
  401: unknown;
  /**
   * Bot already exists for this meeting
   */
  409: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Error creating bot
   */
  500: unknown;
};

export type JoinCallError = JoinCallErrors[keyof JoinCallErrors];

export type JoinCallResponses = {
  /**
   * Successful Response
   */
  200: unknown;
  /**
   * Bot created successfully
   */
  201: unknown;
};
